# Generated by Django 5.0.6 on 2026-07-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('moderator', 'Moderator'), ('institution_admin', 'Institution Admin'), ('system_admin', 'System Admin')], default='citizen', max_length=20),
        ),
    ]
