# Generated by Django 5.0.6 on 2026-07-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('moderator', 'Moderator'), ('legal_editor', 'Legal Editor'), ('institution_admin', 'Institution Admin'), ('national_publisher', 'National Publisher'), ('system_admin', 'System Admin')], default='citizen', max_length=20),
        ),
    ]
