# Generated by Django 5.0.6 on 2026-07-10 13:24

import apps.certificates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "cert_code",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.certificates.models.certificate_pdf_path,
                    ),
                ),
                (
                    "qr_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.certificates.models.certificate_qr_path,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "certificates",
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["cert_code"], name="certificate_cert_co_8e64de_idx"
                    )
                ],
            },
        ),
    ]
