# Generated by Django 5.0.6 on 2026-07-15 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('institutions', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=10, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'certificate_pricing',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='Set only after successful payment — issuance is gated behind this (FR-CERT-02/03).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='payments.payment'),
        ),
    ]
