# Generated by Django 5.0.6 on 2026-07-19 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Human label shown in the UI, e.g. 'Chrome on Windows', 'Android App'.",
                        max_length=100,
                    ),
                ),
                (
                    "device_model",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Samsung Galaxy A14' — sent by Flutter client, blank for web.",
                        max_length=100,
                    ),
                ),
                ("os_name", models.CharField(blank=True, max_length=50)),
                ("os_version", models.CharField(blank=True, max_length=30)),
                ("app_version", models.CharField(blank=True, max_length=30)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "network_type",
                    models.CharField(
                        choices=[
                            ("WIFI", "WiFi"),
                            ("MOBILE_DATA", "Mobile Data"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=15,
                    ),
                ),
                (
                    "location_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Yaoundé, Cameroon' — populate later via IP geolocation lookup if added.",
                        max_length=150,
                    ),
                ),
                (
                    "refresh_token_jti",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="JTI of the SimpleJWT refresh token issued at login, for targeted revocation.",
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Session",
                "verbose_name_plural": "Device Sessions",
                "ordering": ["-last_seen_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="security_de_user_id_5f2f99_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="security_de_ip_addr_18151e_idx"
                    ),
                ],
            },
        ),
    ]
