# Generated by Django 5.0.6 on 2026-07-15 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
         migrations.DeleteModel(
            name='LearningZone',
        ),

        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Unique zone title.', max_length=150, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Frontend icon identifier (heroicons, lucide, material...).', max_length=100)),
                ('color', models.CharField(default='#2563EB', help_text='Hex color used by frontend.', max_length=7)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], db_index=True, default='beginner', max_length=20)),
                ('estimated_hours', models.PositiveSmallIntegerField(default=0, help_text='Estimated hours to complete this learning zone.')),
            ],
            options={
                'verbose_name': 'Learning Zone',
                'verbose_name_plural': 'Learning Zones',
                'db_table': 'learning_zones',
                'ordering': ['display_order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='learning_zo_slug_8e4bb1_idx'), models.Index(fields=['status'], name='learning_zo_status_b8e705_idx'), models.Index(fields=['difficulty'], name='learning_zo_difficu_4b60ea_idx'), models.Index(fields=['display_order'], name='learning_zo_display_7715d5_idx')],
            },
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.zone'),
        ),
       
    ]
