# Generated by Django 5.0.6 on 2026-07-18 17:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("MTN", "MTN Mobile Money"),
                            ("ORANGE", "Orange Money"),
                            ("CARD", "Card Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Internal label, e.g. 'Finance Account 1' — not shown to users.",
                        max_length=100,
                    ),
                ),
                ("account_name", models.CharField(max_length=150)),
                ("account_number", models.CharField(max_length=20)),
                (
                    "reference_code",
                    models.CharField(
                        help_text="Code users should quote as payment reference, e.g. VRN2026.",
                        max_length=50,
                    ),
                ),
                ("instructions", models.TextField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one active configuration per payment_method is served to users.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Configuration",
                "verbose_name_plural": "Payment Configurations",
                "ordering": ["payment_method", "-is_active", "-updated_at"],
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="PaymentSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("TRACKING_FEE", "Tracking Request Fee"),
                            ("INSTITUTION_LICENSE", "Institution Licensing"),
                        ],
                        max_length=30,
                    ),
                ),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                ("payer_name", models.CharField(max_length=150)),
                ("payer_phone", models.CharField(max_length=20)),
                (
                    "amount_expected",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amount_declared",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("transaction_ref", models.CharField(blank=True, max_length=100)),
                ("proof_file", models.FileField(upload_to="documents/payments/%Y/%m/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("PROOF_REQUESTED", "Proof Requested"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("proof_request_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_configuration",
                    models.ForeignKey(
                        help_text="Which account the user was instructed to pay.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="payments.paymentconfiguration",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Submission",
                "verbose_name_plural": "Payment Submissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="payments_pa_status_e05b4b_idx"
                    ),
                    models.Index(
                        fields=["purpose", "related_object_id"],
                        name="payments_pa_purpose_b017c4_idx",
                    ),
                ],
            },
        ),
    ]
