/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./**/*.html', './assets/js/**/*.js'],
  theme: {
    extend: {
      colors: {
        primary: '#002869',
        secondary: '#006d3b',
        tertiary: '#262d33',
        error: '#ba1a1a',
        background: '#f9f9fc',
        surface: '#f9f9fc',
        'surface-variant': '#e2e2e5',
        'surface-container': '#eeeef0',
        'surface-container-low': '#f3f3f6',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e5',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dadadc',
        'surface-bright': '#f9f9fc',
        outline: '#747783',
        'outline-variant': '#c4c6d3',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-surface': '#1a1c1e',
        'on-surface-variant': '#434652',
        'on-background': '#1a1c1e',
        'on-primary-container': '#8dadff',
        'on-secondary-container': '#00723d',
        'on-tertiary-container': '#a9afb8',
        'on-primary-fixed': '#001947',
        'on-primary-fixed-variant': '#144296',
        'on-secondary-fixed': '#00210e',
        'on-secondary-fixed-variant': '#00522b',
        'on-tertiary-fixed': '#161c23',
        'on-tertiary-fixed-variant': '#41474f',
        'on-error-container': '#93000a',
        'primary-container': '#0b3d91',
        'secondary-container': '#78f8a6',
        'tertiary-container': '#3c434a',
        'primary-fixed': '#dae2ff',
        'secondary-fixed': '#7bfba8',
        'tertiary-fixed': '#dde3ec',
        'primary-fixed-dim': '#b1c5ff',
        'secondary-fixed-dim': '#5dde8e',
        'tertiary-fixed-dim': '#c1c7d0',
        'error-container': '#ffdad6',
        'inverse-primary': '#b1c5ff',
        'inverse-surface': '#2f3133',
        'surface-tint': '#345baf'
      },
      fontFamily: {
        'label-lg': ['Work Sans', 'sans-serif'],
        'label-md': ['Work Sans', 'sans-serif'],
        'headline-lg': ['Public Sans', 'sans-serif'],
        'headline-md': ['Public Sans', 'sans-serif'],
        'body-lg': ['Public Sans', 'sans-serif'],
        'body-md': ['Public Sans', 'sans-serif'],
        display: ['Public Sans', 'sans-serif'],
        caption: ['Public Sans', 'sans-serif']
      },
      spacing: {
        unit: '8px',
        'stack-sm': '8px',
        gutter: '24px',
        'stack-md': '16px',
        'section-gap': '64px',
        'margin-desktop': '48px',
        'container-max-width': '1440px',
        'stack-lg': '32px'
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px'
      }
    },
  },
  plugins: [],
}

