# Generated by Django 5.0.6 on 2026-07-12 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'incident_moderation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='financial_loss',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='region',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='title',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='incident',
            name='evidence_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='incident',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='location_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='report_reference',
            field=models.CharField(db_index=True, default='inc-0001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['report_reference'], name='incidents_report__f5ea80_idx'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
