# Generated by Django 5.0.6 on 2026-07-21 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emaillog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
            },
        ),
        migrations.RemoveIndex(
            model_name="emaillog",
            name="email_logs_status_e3be55_idx",
        ),
        migrations.RemoveIndex(
            model_name="emaillog",
            name="email_logs_recipie_df5c2b_idx",
        ),
        migrations.RenameField(
            model_name="emaillog",
            old_name="recipient",
            new_name="to_email",
        ),
        migrations.RemoveField(
            model_name="emaillog",
            name="template_name",
        ),
        migrations.RemoveField(
            model_name="emaillog",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="emaillog",
            name="notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_logs",
                to="notifications.notification",
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="provider",
            field=models.CharField(default="RESEND", max_length=20),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="provider_message_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[("SENT", "Sent"), ("FAILED", "Failed")], max_length=10
            ),
        ),
        migrations.AlterModelTable(
            name="emaillog",
            table=None,
        ),
    ]
